version: "3.0"

services:
  front:
    image: dietis/vuejs:v1
    # container_name: VueJs
    command: npm start
    # build:
      # context: ../timemanager-front/.
      # dockerfile: Dockerfile
    # volumes:
    #   - '../timemanager-front/.:/app'
    #   - '/app/node_modules'
    ports:
      - '8081:8081'

  web:
    # build: .
    image: dietis/elixir:v1
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@mypostgres:5432/timemanager_dev
      - HOSTNAME_URL=mypostgres
    # volumes:
    #   - .:/app
    ports:
      - "4000:4000"
    links:
      - mypostgres
    depends_on:
      - migration

  migration:
    image: dietis/elixir:v1
    command: mix ecto.migrate
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@mypostgres:5432/timemanager_dev
      - HOSTNAME_URL=mypostgres
    # volumes:
      # - .:/code
    links:
      - mypostgres
    depends_on:
      - init

  init:
    image: dietis/elixir:v1
    command: mix ecto.create
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@mypostgres:5432/timemanager_dev
      - HOSTNAME_URL=mypostgres
    # volumes:
      # - .:/code
    links:
      - mypostgres
    depends_on:
      - mypostgres

  mypostgres:
    image: postgres:9.6
    # volumes:
        # - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Xdveg567
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
